version: '2'

services:
  redis-manager:
    build: .
    container_name: redis-manager
    command: --redis-host redis-server
    depends_on:
      - redis
    ports:
      - 8081:8081
    networks:
      - redis-net
  redis:
    container_name: redis-server
    image: redis
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    networks:
      - redis-net

volumes:
  redis-data:

networks:
  redis-net:
    driver: bridge
